import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { readFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import test from "node:test";
import { promisify } from "node:util";

const run = promisify(execFile);
const PROTOCOL = "docs/harness/10-session-protocol.md";

/**
 * `CLAUDE.md` and `AGENTS.md` are ignored install artefacts on a developer
 * machine, so a fresh clone has neither. They are still checked when present:
 * a broken route costs every local session, which is exactly what this test
 * exists to catch.
 */
const ENTRY_POINTS = ["GEMINI.md", "CLAUDE.md", "AGENTS.md", PROTOCOL];

async function readIfPresent(file: string): Promise<string | null> {
  return readFile(resolve(file), "utf8").catch(() => null);
}

/** Every path an entry point routes to, as that entry point spells it. */
function routedPaths(source: string, file: string): string[] {
  const here = dirname(file);
  const imports = [...source.matchAll(/^@(\S+)$/gm)].map(
    (match) => match[1] ?? ""
  );
  const backticked = [...source.matchAll(/`([^`]+\.md)`/g)].map(
    (match) => match[1] ?? ""
  );
  const links = [...source.matchAll(/\]\(([^)#]+\.md)(?:#[^)]+)?\)/g)].map(
    (match) => join(here, match[1] ?? "")
  );
  return [...new Set([...imports, ...backticked, ...links])];
}

test("every routed session path resolves", async () => {
  let checked = 0;
  for (const entry of ENTRY_POINTS) {
    const source = await readIfPresent(entry);
    if (source === null) {
      continue;
    }
    for (const path of routedPaths(source, entry)) {
      checked += 1;
      // ponytail: `.agent-ops/` is generated by install, deliberately
      // ignored, and absent both in a fresh clone and in the read-only
      // snapshot a review runs against. Requiring it would make this test
      // demand local initialization, so it is skipped entirely.
      if (path.startsWith(".agent-ops/")) {
        continue;
      }
      // Tracked, not merely present: an ignored artefact would make the route
      // work on this machine and break in a fresh clone.
      await run("git", ["ls-files", "--error-unmatch", path]);
    }
  }
  assert.ok(checked > 0, "no session route was checked");
});

test("the session protocol routes to every specification module", async () => {
  const source = await readFile(resolve(PROTOCOL), "utf8");
  const { readdir } = await import("node:fs/promises");
  const modules = (await readdir(resolve("docs/en/spec")))
    .filter((file) => file.endsWith(".md") && file !== "README.md");
  for (const module of modules) {
    assert.match(source, new RegExp(module.replace(".", "\\.")), module);
  }
});

test("no entry point promises a specification that does not exist", async () => {
  for (const entry of ENTRY_POINTS) {
    const source = await readIfPresent(entry);
    if (source !== null) {
      assert.doesNotMatch(source, /model dispatch/i, entry);
    }
  }
});
