import { lstat, readFile } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";

import type { Harness, InstallScope } from "../contracts.js";
import { sha256 } from "../fs/hash.js";
import { AgentOpsError, resolveContainedPath } from "../fs/paths.js";
import { FileTransaction, type FileOperation } from "../fs/transaction.js";

/**
 * What a session may do without asking, decided once, when the user confirms
 * init or update: the commands a worktree session runs itself. `trust`,
 * `allow-stop`, `init`, `update` and `uninstall` stay out, so the approvals
 * that are the user's alone remain the user's.
 */
export const CLAUDE_LOCAL_SETTINGS_PATH = ".claude/settings.local.json";
export const CLAUDE_PREAUTH_ALLOW: readonly string[] = [
  "Bash(agent-ops task *)",
  "Bash(agent-ops verify *)",
  "Bash(agent-ops review *)",
  "Bash(agent-ops batch *)",
  "Bash(agent-ops worktree *)",
  "Bash(agent-ops doctor *)",
  // The PreToolUse hook still blocks a path this session does not own.
  "EnterWorktree",
  // A worktree commit runs the project's pre-commit hook, usually this.
  "Bash(npx lint-staged *)"
];
/**
 * review, batch and task advance talk to the reviewer's API, which the sandbox withholds;
 * worktree commit and lint-staged write the main .git, which a worktree's
 * sandbox cannot.
 */
export const CLAUDE_PREAUTH_UNSANDBOXED: readonly string[] = [
  "agent-ops task advance",
  "agent-ops task advance *",
  "agent-ops review",
  "agent-ops review *",
  "agent-ops batch",
  "agent-ops batch *",
  "agent-ops worktree commit",
  "agent-ops worktree commit *",
  "npx lint-staged",
  "npx lint-staged *"
];

export const CODEX_RULES_PATH = "rules/agent-ops.rules";
export const CODEX_RULES_MARKER =
  "# agent-ops managed: regenerated by agent-ops init and update; do not edit.";

const HOSTS = ["AGENT_OPS_HOST=codex", "AGENT_OPS_HOST=claude", "AGENT_OPS_HOST=agy"];
const ENV_PREFIX = ["env", "-u", "CODEX_SANDBOX_NETWORK_DISABLED"];

function starlarkList(values: readonly (string | readonly string[])[]): string {
  return `[${values.map((value) =>
    typeof value === "string"
      ? JSON.stringify(value)
      : `[${value.map((item) => JSON.stringify(item)).join(", ")}]`
  ).join(", ")}]`;
}

function rule(options: {
  readonly withHost: boolean;
  readonly command: readonly string[];
  readonly justification: string;
  readonly match: string;
  readonly notMatch: string;
}): string {
  const pattern = [
    ...ENV_PREFIX,
    ...(options.withHost ? [HOSTS] : []),
    "agent-ops",
    ...options.command
  ];
  return [
    "prefix_rule(",
    `    pattern = ${starlarkList(pattern)},`,
    '    decision = "allow",',
    `    justification = ${JSON.stringify(options.justification)},`,
    `    match = [${JSON.stringify(options.match)}],`,
    `    not_match = [${JSON.stringify(options.notMatch)}]`,
    ")"
  ].join("\n");
}

/**
 * Prefix rules for the exact shapes `.agent-ops/AGENTS.md` tells Codex to run,
 * with and without AGENT_OPS_HOST, for review, batch and the auth probe.
 * Matching is by argv prefix, so a shell redirect would defeat it: use
 * `--output`.
 */
export const CODEX_RULES_CONTENT = `${[
  CODEX_RULES_MARKER,
  ...[
    {
      pattern: ["agent-ops", "worktree", "commit"],
      justification: "agent-ops worktree commit runs git hooks, which write the main .git outside the sandbox.",
      match: "agent-ops worktree commit -m message"
    },
    {
      pattern: ["npx", "lint-staged"],
      justification: "lint-staged backs up through the main .git, which the sandbox cannot write from a worktree.",
      match: "npx lint-staged --debug"
    }
  ].map((entry) => [
    "prefix_rule(",
    `    pattern = ${starlarkList(entry.pattern)},`,
    '    decision = "allow",',
    `    justification = ${JSON.stringify(entry.justification)},`,
    `    match = [${JSON.stringify(entry.match)}],`,
    '    not_match = ["agent-ops trust grant --scope project --yes"]',
    ")"
  ].join("\n")),
  ...[true, false].flatMap((withHost) => {
    const host = withHost ? "AGENT_OPS_HOST=codex " : "";
    const env = `env -u CODEX_SANDBOX_NETWORK_DISABLED ${host}agent-ops`;
    return [
      rule({
        withHost,
        command: ["review"],
        justification: "agent-ops review needs network and loopback outside the sandbox.",
        match: `${env} review --task task-x --yes --output review.json`,
        notMatch: `${env} trust grant --scope project --yes`
      }),
      rule({
        withHost,
        command: ["batch"],
        justification: "agent-ops batch runs reviews, which need network and loopback outside the sandbox.",
        match: `${env} batch --parent task-x --yes --output batch.json`,
        notMatch: `${env} trust grant --scope project --yes`
      }),
      rule({
        withHost,
        command: ["task", "advance"],
        justification: "agent-ops task advance runs the final reviewer chain and finish outside the sandbox.",
        match: `${env} task advance --task task-x --session session-x --yes`,
        notMatch: `${env} trust grant --scope project --yes`
      }),
      rule({
        withHost,
        command: ["doctor", "--check-auth"],
        justification: "agent-ops doctor --check-auth probes review targets, which needs the network outside the sandbox.",
        match: `${env} doctor --check-auth --json --output doctor.json`,
        notMatch: `${env} doctor --scope user`
      })
    ];
  })
].join("\n")}\n`;

export interface PreauthChange {
  /** The directory `operation.path` is relative to: the project, or Codex's home. */
  readonly root: string;
  readonly operation: FileOperation;
  /**
   * What changes, in words. The user's own settings file is not shown to the
   * plan output, which may be logged, so the entries agent-ops adds or removes
   * are the whole disclosure for it.
   */
  readonly summary: string;
  /** True when the whole file content is agent-ops' own and may be shown. */
  readonly ownedContent: boolean;
}

export function codexHomeDirectory(
  env: Readonly<Record<string, string | undefined>> = process.env
): string {
  return env.CODEX_HOME ?? join(env.HOME ?? homedir(), ".codex");
}

interface Current {
  readonly content: string;
  readonly hash: string;
}

async function readCurrent(root: string, path: string): Promise<Current | null> {
  const resolved = await resolveContainedPath(root, path);
  try {
    if (!(await lstat(resolved)).isFile()) {
      throw new AgentOpsError("PREAUTH_TARGET_INVALID", `Pre-authorization target must be a regular file: ${path}`);
    }
    const content = await readFile(resolved, "utf8");
    return { content, hash: sha256(content) };
  } catch (error) {
    if (typeof error === "object" && error !== null && "code" in error && error.code === "ENOENT") {
      return null;
    }
    throw error;
  }
}

function invalidSettings(reason: string, cause?: unknown): AgentOpsError {
  return new AgentOpsError(
    "PREAUTH_SETTINGS_INVALID",
    `${CLAUDE_LOCAL_SETTINGS_PATH} ${reason}; fix it or remove it, then run agent-ops update.`,
    cause === undefined ? undefined : { cause }
  );
}

function stringList(value: unknown, where: string): string[] {
  if (value === undefined) {
    return [];
  }
  if (!Array.isArray(value) || value.some((item) => typeof item !== "string")) {
    throw invalidSettings(`has a ${where} that is not a list of strings`);
  }
  return [...value] as string[];
}

/**
 * The managed entries merged into, or stripped from, the user's own local
 * settings. Nothing else in the file is touched. `null` content means the file
 * held nothing but these entries and should go; `undefined` means no change.
 */
export function planClaudeLocalSettings(
  source: string | null,
  desired: boolean
): { readonly content: string | null } | undefined {
  let settings: Record<string, unknown> = {};
  if (source !== null && source.trim() !== "") {
    let parsed: unknown;
    try {
      parsed = JSON.parse(source) as unknown;
    } catch (error) {
      throw invalidSettings("is not valid JSON", error);
    }
    if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
      throw invalidSettings("is not a JSON object");
    }
    settings = parsed as Record<string, unknown>;
  }
  const permissions = (settings.permissions ?? {}) as Record<string, unknown>;
  const sandbox = (settings.sandbox ?? {}) as Record<string, unknown>;
  if (typeof permissions !== "object" || Array.isArray(permissions) ||
    typeof sandbox !== "object" || Array.isArray(sandbox)) {
    throw invalidSettings("has a permissions or sandbox entry that is not an object");
  }
  const allow = stringList(permissions.allow, "permissions.allow");
  const excluded = stringList(sandbox.excludedCommands, "sandbox.excludedCommands");
  const merge = (current: string[], managed: readonly string[]): string[] =>
    desired
      ? [...current, ...managed.filter((entry) => !current.includes(entry))]
      : current.filter((entry) => !managed.includes(entry));
  const nextAllow = merge(allow, CLAUDE_PREAUTH_ALLOW);
  const nextExcluded = merge(excluded, CLAUDE_PREAUTH_UNSANDBOXED);
  if (nextAllow.length === allow.length && nextExcluded.length === excluded.length &&
    nextAllow.every((entry, index) => entry === allow[index]) &&
    nextExcluded.every((entry, index) => entry === excluded[index])) {
    return undefined;
  }
  const { allow: _allow, ...otherPermissions } = permissions;
  const { excludedCommands: _excluded, ...otherSandbox } = sandbox;
  const nextPermissions = {
    ...otherPermissions,
    ...(nextAllow.length === 0 ? {} : { allow: nextAllow })
  };
  const nextSandbox = {
    ...otherSandbox,
    ...(nextExcluded.length === 0 ? {} : { excludedCommands: nextExcluded })
  };
  const { permissions: _p, sandbox: _s, ...rest } = settings;
  const next = {
    ...rest,
    ...(Object.keys(nextPermissions).length === 0 ? {} : { permissions: nextPermissions }),
    ...(Object.keys(nextSandbox).length === 0 ? {} : { sandbox: nextSandbox })
  };
  return {
    content: Object.keys(next).length === 0 ? null : `${JSON.stringify(next, null, 2)}\n`
  };
}

async function claudeChange(
  root: string,
  desired: boolean
): Promise<PreauthChange | undefined> {
  const current = await readCurrent(root, CLAUDE_LOCAL_SETTINGS_PATH);
  const planned = planClaudeLocalSettings(current?.content ?? null, desired);
  if (planned === undefined) {
    return undefined;
  }
  const summary = desired
    ? `Adds to ${CLAUDE_LOCAL_SETTINGS_PATH} (existing entries kept): permissions.allow ` +
      `${JSON.stringify(CLAUDE_PREAUTH_ALLOW)}; sandbox.excludedCommands ${JSON.stringify(CLAUDE_PREAUTH_UNSANDBOXED)}.`
    : `Removes the agent-ops entries from ${CLAUDE_LOCAL_SETTINGS_PATH}, keeping everything else.`;
  if (planned.content === null) {
    return current === null
      ? undefined
      : {
          root,
          operation: { kind: "remove", path: CLAUDE_LOCAL_SETTINGS_PATH, expectedHash: current.hash },
          summary,
          ownedContent: false
        };
  }
  return {
    root,
    operation: {
      kind: "write",
      path: CLAUDE_LOCAL_SETTINGS_PATH,
      content: planned.content,
      expectedHash: current?.hash ?? null
    },
    summary,
    ownedContent: false
  };
}

async function codexChange(
  codexHome: string,
  desired: boolean
): Promise<PreauthChange | undefined> {
  const isDirectory = await lstat(codexHome).then((status) => status.isDirectory(), () => false);
  if (!isDirectory) {
    return undefined;
  }
  const current = await readCurrent(codexHome, CODEX_RULES_PATH);
  // A rules file of the same name that agent-ops did not write is not ours to
  // overwrite or delete.
  if (current !== null && !current.content.startsWith(CODEX_RULES_MARKER)) {
    return undefined;
  }
  if (!desired) {
    return current === null
      ? undefined
      : {
          root: codexHome,
          operation: { kind: "remove", path: CODEX_RULES_PATH, expectedHash: current.hash },
          summary: `Removes ${join(codexHome, CODEX_RULES_PATH)}, the rules agent-ops wrote.`,
          ownedContent: true
        };
  }
  return current?.content === CODEX_RULES_CONTENT
    ? undefined
    : {
        root: codexHome,
        operation: {
          kind: "write",
          path: CODEX_RULES_PATH,
          content: CODEX_RULES_CONTENT,
          expectedHash: current?.hash ?? null
        },
        summary: `Writes ${join(codexHome, CODEX_RULES_PATH)}: allow rules for agent-ops review, batch, doctor --check-auth, worktree commit and lint-staged.`,
        ownedContent: true
      };
}

/**
 * What init, update and uninstall change beyond the manifest: the local Claude
 * settings entries and the Codex rules file. Project scope only; `desired`
 * false plans the removal of what agent-ops wrote.
 */
export async function planPreauth(options: {
  readonly root: string;
  readonly scope: InstallScope;
  readonly harness: Harness;
  readonly desired: boolean;
  readonly codexHome?: string;
}): Promise<readonly PreauthChange[]> {
  if (options.scope !== "project") {
    return [];
  }
  const changes: (PreauthChange | undefined)[] = [];
  if (options.harness.includes("claude")) {
    changes.push(await claudeChange(options.root, options.desired));
  }
  // Codex's home is outside the project, so it is only touched when the caller
  // names it (the CLI does): planning alone must never reach into a real home.
  if (options.harness.includes("codex") && options.codexHome !== undefined) {
    changes.push(await codexChange(options.codexHome, options.desired));
  }
  return changes.filter((change): change is PreauthChange => change !== undefined);
}

export async function applyPreauth(changes: readonly PreauthChange[]): Promise<void> {
  for (const change of changes) {
    try {
      await new FileTransaction(change.root).apply({ operations: [change.operation] });
    } catch (error) {
      throw new AgentOpsError(
        "PREAUTH_APPLY_FAILED",
        `The rest was applied, but ${join(change.root, change.operation.path)} was not written; fix that file and run agent-ops update.`,
        { cause: error }
      );
    }
  }
}
